export enum NotificationType {
  RESERVATION_CONFIRMATION = 'RESERVATION_CONFIRMATION',
  RESERVATION_REMINDER = 'RESERVATION_REMINDER',
  SUSCRIPTION_EXPIRING = 'SUSCRIPTION_EXPIRING',
  SUSCRIPTION_PAYMENT_REMINDER = 'SUSCRIPTION_PAYMENT_REMINDER',
}
